version: '3.7'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: mysql
    command: --disable-partition-engine-check
    environment:
      - MYSQL_DATABASE=pay
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    ports:
      - '3307:3306'

  spring:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=pay
      - DATABASE_PORT=3307
    depends_on:
      - mysql
